-- File generated by the BNF Converter (bnfc 2.9.7).

{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}

-- | Pretty-printer for REQ.

module REQ.Print where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified REQ.Abs

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 False (map ($ "") $ d []) ""
  where
  rend
    :: Int        -- ^ Indentation level.
    -> Bool       -- ^ Pending indentation to be output before next character?
    -> [String]
    -> ShowS
  rend i p = \case
      "["      :ts -> char '[' . rend i False ts
      "("      :ts -> char '(' . rend i False ts
      "{"      :ts -> onNewLine i     p . showChar   '{'  . new (i+1) ts
      "}" : ";":ts -> onNewLine (i-1) p . showString "};" . new (i-1) ts
      "}"      :ts -> onNewLine (i-1) p . showChar   '}'  . new (i-1) ts
      [";"]        -> char ';'
      ";"      :ts -> char ';' . new i ts
      t  : ts@(s:_) | closingOrPunctuation s
                   -> pending . showString t . rend i False ts
      t        :ts -> pending . space t      . rend i False ts
      []           -> id
    where
    -- Output character after pending indentation.
    char :: Char -> ShowS
    char c = pending . showChar c

    -- Output pending indentation.
    pending :: ShowS
    pending = if p then indent i else id

  -- Indentation (spaces) for given indentation level.
  indent :: Int -> ShowS
  indent i = replicateS (2*i) (showChar ' ')

  -- Continue rendering in new line with new indentation.
  new :: Int -> [String] -> ShowS
  new j ts = showChar '\n' . rend j True ts

  -- Make sure we are on a fresh line.
  onNewLine :: Int -> Bool -> ShowS
  onNewLine i p = (if p then id else showChar '\n') . indent i

  -- Separate given string from following text by a space (if needed).
  space :: String -> ShowS
  space t s =
    case (all isSpace t, null spc, null rest) of
      (True , _   , True ) -> []             -- remove trailing space
      (False, _   , True ) -> t              -- remove trailing space
      (False, True, False) -> t ++ ' ' : s   -- add space if none
      _                    -> t ++ s
    where
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt i = concatD . map (prt i)

instance Print Char where
  prt _ c = doc (showChar '\'' . mkEsc '\'' c . showChar '\'')

instance Print String where
  prt _ = printString

printString :: String -> Doc
printString s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print REQ.Abs.DynVar where
  prt _ (REQ.Abs.DynVar i) = doc $ showString i
instance Print REQ.Abs.Theory where
  prt i = \case
    REQ.Abs.Thry dynvar dynvars items -> prPrec i 0 (concatD [doc (showString "Theory"), prt 0 dynvar, doc (showString "."), prt 0 dynvars, doc (showString "."), prt 0 items])

instance Print [REQ.Abs.DynVar] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print REQ.Abs.Item where
  prt i = \case
    REQ.Abs.DeclVar varclass dynvar varrole -> prPrec i 0 (concatD [doc (showString "DclVar"), prt 0 varclass, prt 0 dynvar, doc (showString "."), prt 0 varrole, doc (showString ".")])
    REQ.Abs.DeclDLVar varclass dynvar dynvars -> prPrec i 0 (concatD [doc (showString "DclDLVar"), prt 0 varclass, prt 0 dynvar, doc (showString "."), prt 0 dynvars, doc (showString ".")])
    REQ.Abs.DeclASet varclass dynvar -> prPrec i 0 (concatD [doc (showString "DclASet"), prt 0 varclass, prt 0 dynvar, doc (showString ".")])
    REQ.Abs.Conj dynvar term scond -> prPrec i 0 (concatD [doc (showString "Conjecture"), prt 0 dynvar, doc (showString "."), prt 0 term, doc (showString "."), prt 0 scond])
    REQ.Abs.Law lawtype dynvar term scond -> prPrec i 0 (concatD [doc (showString "Law"), prt 0 lawtype, prt 0 dynvar, doc (showString "."), prt 0 term, doc (showString "."), prt 0 scond])

instance Print REQ.Abs.VarRole where
  prt i = \case
    REQ.Abs.VMR_KV sbbl type_ -> prPrec i 0 (concatD [doc (showString "var"), prt 0 sbbl, prt 0 type_])

instance Print REQ.Abs.VarClass where
  prt i = \case
    REQ.Abs.VarObs -> prPrec i 0 (concatD [doc (showString "Obs")])
    REQ.Abs.VarExp -> prPrec i 0 (concatD [doc (showString "Exp")])
    REQ.Abs.VarPred -> prPrec i 0 (concatD [doc (showString "Prd")])

instance Print REQ.Abs.SBBL where
  prt i = \case
    REQ.Abs.SBBL_NA -> prPrec i 0 (concatD [doc (showString "NA")])
    REQ.Abs.SBBL_SB -> prPrec i 0 (concatD [doc (showString "SB")])
    REQ.Abs.SBBL_NS -> prPrec i 0 (concatD [doc (showString "NS")])

instance Print REQ.Abs.LawType where
  prt i = \case
    REQ.Abs.LAxiom -> prPrec i 0 (concatD [doc (showString "axiom")])
    REQ.Abs.LProof -> prPrec i 0 (concatD [doc (showString "proven")])
    REQ.Abs.LAssume -> prPrec i 0 (concatD [doc (showString "assumed")])

instance Print [REQ.Abs.Item] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print REQ.Abs.Term where
  prt i = \case
    REQ.Abs.PEqv term1 term2 -> prPrec i 0 (concatD [prt 0 term1, doc (showString "==="), prt 1 term2])
    REQ.Abs.PImpl term1 term2 -> prPrec i 1 (concatD [prt 2 term1, doc (showString "==>"), prt 1 term2])
    REQ.Abs.POr term1 term2 -> prPrec i 2 (concatD [prt 2 term1, doc (showString "\\/"), prt 3 term2])
    REQ.Abs.PAnd term1 term2 -> prPrec i 3 (concatD [prt 3 term1, doc (showString "/\\"), prt 4 term2])
    REQ.Abs.PNot term -> prPrec i 3 (concatD [doc (showString "~"), prt 4 term])
    REQ.Abs.EQ term1 term2 -> prPrec i 4 (concatD [prt 5 term1, doc (showString "=="), prt 5 term2])
    REQ.Abs.NE term1 term2 -> prPrec i 4 (concatD [prt 5 term1, doc (showString "!="), prt 5 term2])
    REQ.Abs.LT term1 term2 -> prPrec i 4 (concatD [prt 5 term1, doc (showString "<"), prt 5 term2])
    REQ.Abs.LE term1 term2 -> prPrec i 4 (concatD [prt 5 term1, doc (showString "<="), prt 5 term2])
    REQ.Abs.GT term1 term2 -> prPrec i 4 (concatD [prt 5 term1, doc (showString ">"), prt 5 term2])
    REQ.Abs.GE term1 term2 -> prPrec i 4 (concatD [prt 5 term1, doc (showString ">="), prt 5 term2])
    REQ.Abs.PTrue -> prPrec i 4 (concatD [doc (showString "True")])
    REQ.Abs.PFalse -> prPrec i 4 (concatD [doc (showString "False")])
    REQ.Abs.PVar dynvar -> prPrec i 4 (concatD [prt 0 dynvar])
    REQ.Abs.LCat term1 term2 -> prPrec i 5 (concatD [prt 6 term1, doc (showString "++"), prt 5 term2])
    REQ.Abs.LCons term1 term2 -> prPrec i 5 (concatD [prt 6 term1, doc (showString ":"), prt 5 term2])
    REQ.Abs.EAdd term1 term2 -> prPrec i 6 (concatD [prt 6 term1, doc (showString "+"), prt 7 term2])
    REQ.Abs.EMinus term1 term2 -> prPrec i 6 (concatD [prt 6 term1, doc (showString "-"), prt 7 term2])
    REQ.Abs.EMul term1 term2 -> prPrec i 7 (concatD [prt 7 term1, doc (showString "*"), prt 8 term2])
    REQ.Abs.EDiv term1 term2 -> prPrec i 7 (concatD [prt 7 term1, doc (showString "div"), prt 8 term2])
    REQ.Abs.EMod term1 term2 -> prPrec i 7 (concatD [prt 7 term1, doc (showString "mod"), prt 8 term2])
    REQ.Abs.ENeg term -> prPrec i 7 (concatD [doc (showString "neg"), prt 8 term])
    REQ.Abs.EInt n -> prPrec i 8 (concatD [prt 0 n])
    REQ.Abs.EVar dynvar -> prPrec i 8 (concatD [prt 0 dynvar])
    REQ.Abs.ETrue -> prPrec i 8 (concatD [doc (showString "true")])
    REQ.Abs.EFalse -> prPrec i 8 (concatD [doc (showString "false")])
    REQ.Abs.ENil -> prPrec i 8 (concatD [doc (showString "nil")])
    REQ.Abs.TCons dynvar terms -> prPrec i 8 (concatD [prt 0 dynvar, doc (showString "("), prt 0 terms, doc (showString ")")])
    REQ.Abs.TSubV term terms dynvars -> prPrec i 8 (concatD [doc (showString "SubV"), prt 0 term, doc (showString "[."), prt 0 terms, doc (showString "/"), prt 0 dynvars, doc (showString ".]")])
    REQ.Abs.TSubLV term dynvars1 dynvars2 -> prPrec i 8 (concatD [doc (showString "SubL"), prt 0 term, doc (showString "[."), prt 0 dynvars1, doc (showString "/"), prt 0 dynvars2, doc (showString ".]")])
    REQ.Abs.TSubst term terms dynvars1 dynvars2 dynvars3 -> prPrec i 8 (concatD [doc (showString "Sub"), prt 0 term, doc (showString "[."), prt 0 terms, doc (showString "/"), prt 0 dynvars1, doc (showString "|"), prt 0 dynvars2, doc (showString "/"), prt 0 dynvars3, doc (showString ".]")])

instance Print [REQ.Abs.Term] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print REQ.Abs.Type where
  prt i = \case
    REQ.Abs.TFun type_1 type_2 -> prPrec i 0 (concatD [prt 1 type_1, doc (showString "->"), prt 0 type_2])
    REQ.Abs.TRec dynvar types -> prPrec i 1 (concatD [prt 0 dynvar, doc (showString "(:"), prt 2 types, doc (showString ":)")])
    REQ.Abs.TProd dynvar types -> prPrec i 2 (concatD [prt 0 dynvar, prt 3 types])
    REQ.Abs.TArb -> prPrec i 3 (concatD [doc (showString "ttop")])
    REQ.Abs.TVar dynvar -> prPrec i 3 (concatD [prt 0 dynvar])
    REQ.Abs.TBot -> prPrec i 3 (concatD [doc (showString "tbot")])

instance Print [REQ.Abs.Type] where
  prt 3 [] = concatD []
  prt 3 (x:xs) = concatD [prt 3 x, prt 3 xs]
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 2 x]
  prt _ (x:xs) = concatD [prt 2 x, doc (showString "|"), prt 2 xs]

instance Print REQ.Abs.GVar where
  prt i = \case
    REQ.Abs.SVar dynvar -> prPrec i 0 (concatD [doc (showString "std"), prt 0 dynvar])
    REQ.Abs.LVar dynvar -> prPrec i 0 (concatD [doc (showString "lst"), prt 0 dynvar])

instance Print [REQ.Abs.GVar] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print REQ.Abs.VarSet where
  prt i = \case
    REQ.Abs.VSet gvars -> prPrec i 0 (concatD [prt 0 gvars])

instance Print REQ.Abs.VSCond where
  prt i = \case
    REQ.Abs.VSCDisj gvar varset -> prPrec i 0 (concatD [prt 0 gvar, doc (showString "disj"), prt 0 varset])
    REQ.Abs.VSCCovBy gvar varset -> prPrec i 0 (concatD [prt 0 gvar, doc (showString "covby"), prt 0 varset])
    REQ.Abs.VSCDynCov gvar varset -> prPrec i 0 (concatD [prt 0 gvar, doc (showString "dcovby"), prt 0 varset])

instance Print [REQ.Abs.VSCond] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]

instance Print REQ.Abs.SCond where
  prt i = \case
    REQ.Abs.SCFull vsconds varset -> prPrec i 0 (concatD [doc (showString "SC"), prt 0 vsconds, doc (showString "."), prt 0 varset, doc (showString ".")])
    REQ.Abs.SCVSCs vsconds -> prPrec i 0 (concatD [doc (showString "VSC"), prt 0 vsconds, doc (showString ".")])
    REQ.Abs.SCFresh varset -> prPrec i 0 (concatD [doc (showString "fresh"), prt 0 varset, doc (showString ".")])
    REQ.Abs.SCnone -> prPrec i 0 (concatD [doc (showString "none")])
