-- File generated by the BNF Converter (bnfc 2.9.7).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -Wno-unused-matches #-}

module REQ.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified REQ.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transDynVar :: REQ.Abs.DynVar -> Result
transDynVar x = case x of
  REQ.Abs.DynVar string -> failure x

transTheory :: REQ.Abs.Theory -> Result
transTheory x = case x of
  REQ.Abs.Thry dynvar dynvars items -> failure x

transItem :: REQ.Abs.Item -> Result
transItem x = case x of
  REQ.Abs.DeclVar varclass dynvar varrole -> failure x
  REQ.Abs.DeclDLVar varclass dynvar dynvars -> failure x
  REQ.Abs.DeclASet varclass dynvar -> failure x
  REQ.Abs.Conj dynvar term scond -> failure x
  REQ.Abs.Law lawtype dynvar term scond -> failure x

transVarRole :: REQ.Abs.VarRole -> Result
transVarRole x = case x of
  REQ.Abs.VMR_KV sbbl type_ -> failure x

transVarClass :: REQ.Abs.VarClass -> Result
transVarClass x = case x of
  REQ.Abs.VarObs -> failure x
  REQ.Abs.VarExp -> failure x
  REQ.Abs.VarPred -> failure x

transSBBL :: REQ.Abs.SBBL -> Result
transSBBL x = case x of
  REQ.Abs.SBBL_NA -> failure x
  REQ.Abs.SBBL_SB -> failure x
  REQ.Abs.SBBL_NS -> failure x

transLawType :: REQ.Abs.LawType -> Result
transLawType x = case x of
  REQ.Abs.LAxiom -> failure x
  REQ.Abs.LProof -> failure x
  REQ.Abs.LAssume -> failure x

transTerm :: REQ.Abs.Term -> Result
transTerm x = case x of
  REQ.Abs.PEqv term1 term2 -> failure x
  REQ.Abs.PImpl term1 term2 -> failure x
  REQ.Abs.POr term1 term2 -> failure x
  REQ.Abs.PAnd term1 term2 -> failure x
  REQ.Abs.PNot term -> failure x
  REQ.Abs.EQ term1 term2 -> failure x
  REQ.Abs.NE term1 term2 -> failure x
  REQ.Abs.LT term1 term2 -> failure x
  REQ.Abs.LE term1 term2 -> failure x
  REQ.Abs.GT term1 term2 -> failure x
  REQ.Abs.GE term1 term2 -> failure x
  REQ.Abs.PTrue -> failure x
  REQ.Abs.PFalse -> failure x
  REQ.Abs.PVar dynvar -> failure x
  REQ.Abs.LCat term1 term2 -> failure x
  REQ.Abs.LCons term1 term2 -> failure x
  REQ.Abs.EAdd term1 term2 -> failure x
  REQ.Abs.EMinus term1 term2 -> failure x
  REQ.Abs.EMul term1 term2 -> failure x
  REQ.Abs.EDiv term1 term2 -> failure x
  REQ.Abs.EMod term1 term2 -> failure x
  REQ.Abs.ENeg term -> failure x
  REQ.Abs.EInt integer -> failure x
  REQ.Abs.EVar dynvar -> failure x
  REQ.Abs.ETrue -> failure x
  REQ.Abs.EFalse -> failure x
  REQ.Abs.ENil -> failure x
  REQ.Abs.TCons dynvar terms -> failure x
  REQ.Abs.TSubV term terms dynvars -> failure x
  REQ.Abs.TSubLV term dynvars1 dynvars2 -> failure x
  REQ.Abs.TSubst term terms dynvars1 dynvars2 dynvars3 -> failure x

transType :: REQ.Abs.Type -> Result
transType x = case x of
  REQ.Abs.TFun type_1 type_2 -> failure x
  REQ.Abs.TRec dynvar types -> failure x
  REQ.Abs.TProd dynvar types -> failure x
  REQ.Abs.TArb -> failure x
  REQ.Abs.TVar dynvar -> failure x
  REQ.Abs.TBot -> failure x

transGVar :: REQ.Abs.GVar -> Result
transGVar x = case x of
  REQ.Abs.SVar dynvar -> failure x
  REQ.Abs.LVar dynvar -> failure x

transVarSet :: REQ.Abs.VarSet -> Result
transVarSet x = case x of
  REQ.Abs.VSet gvars -> failure x

transVSCond :: REQ.Abs.VSCond -> Result
transVSCond x = case x of
  REQ.Abs.VSCDisj gvar varset -> failure x
  REQ.Abs.VSCCovBy gvar varset -> failure x
  REQ.Abs.VSCDynCov gvar varset -> failure x

transSCond :: REQ.Abs.SCond -> Result
transSCond x = case x of
  REQ.Abs.SCFull vsconds varset -> failure x
  REQ.Abs.SCVSCs vsconds -> failure x
  REQ.Abs.SCFresh varset -> failure x
  REQ.Abs.SCnone -> failure x
