-- File generated by the BNF Converter (bnfc 2.9.7).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -Wno-unused-matches #-}

module REQ.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified REQ.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transDynVar :: REQ.Abs.DynVar -> Result
transDynVar x = case x of
  REQ.Abs.DynVar string -> failure x

transThry :: REQ.Abs.Thry -> Result
transThry x = case x of
  REQ.Abs.Thr dynvar dynvars items -> failure x

transItem :: REQ.Abs.Item -> Result
transItem x = case x of
  REQ.Abs.DefObs dynvars -> failure x
  REQ.Abs.DefExpr dynvars -> failure x
  REQ.Abs.DefPred dynvars -> failure x
  REQ.Abs.DefStatic dynvars -> failure x
  REQ.Abs.DeclVar vclass dynvar varrole -> failure x
  REQ.Abs.DeclDLVar vclass dynvar dynvars -> failure x
  REQ.Abs.DeclASet vclass dynvar -> failure x
  REQ.Abs.Conj dynvar trm scond -> failure x
  REQ.Abs.Law lawtype dynvar trm scond -> failure x

transVarRole :: REQ.Abs.VarRole -> Result
transVarRole x = case x of
  REQ.Abs.KV sbbl typ -> failure x

transVClass :: REQ.Abs.VClass -> Result
transVClass x = case x of
  REQ.Abs.VarObs -> failure x
  REQ.Abs.VarExp -> failure x
  REQ.Abs.VarPred -> failure x

transSBBL :: REQ.Abs.SBBL -> Result
transSBBL x = case x of
  REQ.Abs.Na -> failure x
  REQ.Abs.SB -> failure x
  REQ.Abs.NS -> failure x

transLawType :: REQ.Abs.LawType -> Result
transLawType x = case x of
  REQ.Abs.LAxiom -> failure x
  REQ.Abs.LProof -> failure x
  REQ.Abs.LAssume -> failure x

transTrm :: REQ.Abs.Trm -> Result
transTrm x = case x of
  REQ.Abs.PEqv trm1 trm2 -> failure x
  REQ.Abs.PImpl trm1 trm2 -> failure x
  REQ.Abs.POr trm1 trm2 -> failure x
  REQ.Abs.PAnd trm1 trm2 -> failure x
  REQ.Abs.PNot trm -> failure x
  REQ.Abs.Eql trm1 trm2 -> failure x
  REQ.Abs.NE trm1 trm2 -> failure x
  REQ.Abs.Lt trm1 trm2 -> failure x
  REQ.Abs.LE trm1 trm2 -> failure x
  REQ.Abs.Gt trm1 trm2 -> failure x
  REQ.Abs.GE trm1 trm2 -> failure x
  REQ.Abs.LCat trm1 trm2 -> failure x
  REQ.Abs.LCons trm1 trm2 -> failure x
  REQ.Abs.EAdd trm1 trm2 -> failure x
  REQ.Abs.EMinus trm1 trm2 -> failure x
  REQ.Abs.EMul trm1 trm2 -> failure x
  REQ.Abs.EDiv trm1 trm2 -> failure x
  REQ.Abs.EMod trm1 trm2 -> failure x
  REQ.Abs.ENeg trm -> failure x
  REQ.Abs.EInt integer -> failure x
  REQ.Abs.TmVar dynvar -> failure x
  REQ.Abs.TTrue -> failure x
  REQ.Abs.TFalse -> failure x
  REQ.Abs.ENil -> failure x
  REQ.Abs.TCons dynvar trms -> failure x
  REQ.Abs.TSubV trm trms dynvars -> failure x
  REQ.Abs.TSubLV trm dynvars1 dynvars2 -> failure x
  REQ.Abs.TSubst trm trms dynvars1 dynvars2 dynvars3 -> failure x

transTyp :: REQ.Abs.Typ -> Result
transTyp x = case x of
  REQ.Abs.TFun typ1 typ2 -> failure x
  REQ.Abs.TRec dynvar typs -> failure x
  REQ.Abs.TProd dynvar typs -> failure x
  REQ.Abs.TArb -> failure x
  REQ.Abs.TVbl dynvar -> failure x
  REQ.Abs.TBot -> failure x

transGVar :: REQ.Abs.GVar -> Result
transGVar x = case x of
  REQ.Abs.SVar dynvar -> failure x
  REQ.Abs.LVar dynvar -> failure x

transVrSet :: REQ.Abs.VrSet -> Result
transVrSet x = case x of
  REQ.Abs.VSet gvars -> failure x

transVSCond :: REQ.Abs.VSCond -> Result
transVSCond x = case x of
  REQ.Abs.VSCDisj gvar vrset -> failure x
  REQ.Abs.VSCCovBy gvar vrset -> failure x
  REQ.Abs.VSCDynCov gvar vrset -> failure x

transSCond :: REQ.Abs.SCond -> Result
transSCond x = case x of
  REQ.Abs.SCFull vsconds vrset -> failure x
  REQ.Abs.SCVSCs vsconds -> failure x
  REQ.Abs.SCFresh vrset -> failure x
  REQ.Abs.SCnone -> failure x
