-- File generated by the BNF Converter (bnfc 2.9.7).

{-# LANGUAGE GeneralizedNewtypeDeriving #-}

-- | The abstract syntax of language UTP.

module UTP.Abs where

import Prelude (Integer, String)
import qualified Prelude as C (Eq, Ord, Show, Read)
import qualified Data.String

data Pred
    = PEqv Pred Pred
    | PImpl Pred Pred
    | POr Pred Pred
    | PAnd Pred Pred
    | PNot Pred
    | PAtomic Exp
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Exp
    = EAdd Exp Exp
    | ESub Exp Exp
    | EMul Exp Exp
    | EDiv Exp Exp
    | EInt Integer
    | EVar Ident
    | EBool Boolean
  deriving (C.Eq, C.Ord, C.Show, C.Read)

newtype Ident = Ident String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

newtype Boolean = Boolean String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

