-- File generated by the BNF Converter (bnfc 2.9.7).

-- | The abstract syntax of language UTP.

module UTP.Abs where

import Prelude (Integer)
import qualified Prelude as C (Eq, Ord, Show, Read)

data Exp
    = EAdd Exp Exp
    | ESub Exp Exp
    | EMul Exp Exp
    | EDiv Exp Exp
    | EInt Integer
  deriving (C.Eq, C.Ord, C.Show, C.Read)

