-- File generated by the BNF Converter (bnfc 2.9.7).

{-# LANGUAGE GeneralizedNewtypeDeriving #-}

-- | The abstract syntax of language UTP.

module UTP.Abs where

import Prelude (Integer, String)
import qualified Prelude as C (Eq, Ord, Show, Read)
import qualified Data.String

data Pred
    = PEqv Pred Pred
    | PImpl Pred Pred
    | POr Pred Pred
    | PAnd Pred Pred
    | PNot Pred
    | EQ Exp Exp
    | NE Exp Exp
    | LT Exp Exp
    | LE Exp Exp
    | GT Exp Exp
    | GE Exp Exp
    | PVar DynVar
    | PExpr Exp
    | PType Type
    | PredTX DynVar [Pred]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Exp
    = ECat Exp Exp
    | ECons Exp Exp
    | EAdd Exp Exp
    | ESub Exp Exp
    | EMul Exp Exp
    | EDiv Exp Exp
    | EMod Exp Exp
    | ENeg Exp
    | EInt Integer
    | EVar DynVar
    | EBool Boolean
    | ENil
    | ENmdTuple DynVar [Exp]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Type
    = TFun Type Type
    | TRec DynVar [Type]
    | TProd DynVar [Type]
    | TArb
    | TVar DynVar
    | TBot
  deriving (C.Eq, C.Ord, C.Show, C.Read)

newtype Boolean = Boolean String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

newtype DynVar = DynVar String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

