-- File generated by the BNF Converter (bnfc 2.9.7).

{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}

-- | Pretty-printer for UTP.

module UTP.Print where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified UTP.Abs

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 False (map ($ "") $ d []) ""
  where
  rend
    :: Int        -- ^ Indentation level.
    -> Bool       -- ^ Pending indentation to be output before next character?
    -> [String]
    -> ShowS
  rend i p = \case
      "["      :ts -> char '[' . rend i False ts
      "("      :ts -> char '(' . rend i False ts
      "{"      :ts -> onNewLine i     p . showChar   '{'  . new (i+1) ts
      "}" : ";":ts -> onNewLine (i-1) p . showString "};" . new (i-1) ts
      "}"      :ts -> onNewLine (i-1) p . showChar   '}'  . new (i-1) ts
      [";"]        -> char ';'
      ";"      :ts -> char ';' . new i ts
      t  : ts@(s:_) | closingOrPunctuation s
                   -> pending . showString t . rend i False ts
      t        :ts -> pending . space t      . rend i False ts
      []           -> id
    where
    -- Output character after pending indentation.
    char :: Char -> ShowS
    char c = pending . showChar c

    -- Output pending indentation.
    pending :: ShowS
    pending = if p then indent i else id

  -- Indentation (spaces) for given indentation level.
  indent :: Int -> ShowS
  indent i = replicateS (2*i) (showChar ' ')

  -- Continue rendering in new line with new indentation.
  new :: Int -> [String] -> ShowS
  new j ts = showChar '\n' . rend j True ts

  -- Make sure we are on a fresh line.
  onNewLine :: Int -> Bool -> ShowS
  onNewLine i p = (if p then id else showChar '\n') . indent i

  -- Separate given string from following text by a space (if needed).
  space :: String -> ShowS
  space t s =
    case (all isSpace t, null spc, null rest) of
      (True , _   , True ) -> []             -- remove trailing space
      (False, _   , True ) -> t              -- remove trailing space
      (False, True, False) -> t ++ ' ' : s   -- add space if none
      _                    -> t ++ s
    where
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt i = concatD . map (prt i)

instance Print Char where
  prt _ c = doc (showChar '\'' . mkEsc '\'' c . showChar '\'')

instance Print String where
  prt _ = printString

printString :: String -> Doc
printString s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print UTP.Abs.Boolean where
  prt _ (UTP.Abs.Boolean i) = doc $ showString i
instance Print UTP.Abs.DynVar where
  prt _ (UTP.Abs.DynVar i) = doc $ showString i
instance Print UTP.Abs.Pred where
  prt i = \case
    UTP.Abs.PEqv pred1 pred2 -> prPrec i 0 (concatD [prt 0 pred1, doc (showString "==="), prt 1 pred2])
    UTP.Abs.PImpl pred1 pred2 -> prPrec i 1 (concatD [prt 2 pred1, doc (showString "==>"), prt 1 pred2])
    UTP.Abs.POr pred1 pred2 -> prPrec i 2 (concatD [prt 2 pred1, doc (showString "\\/"), prt 3 pred2])
    UTP.Abs.PAnd pred1 pred2 -> prPrec i 3 (concatD [prt 3 pred1, doc (showString "/\\"), prt 4 pred2])
    UTP.Abs.PNot pred -> prPrec i 4 (concatD [doc (showString "~"), prt 5 pred])
    UTP.Abs.EQ exp1 exp2 -> prPrec i 5 (concatD [prt 0 exp1, doc (showString "=="), prt 0 exp2])
    UTP.Abs.NE exp1 exp2 -> prPrec i 5 (concatD [prt 0 exp1, doc (showString "!="), prt 0 exp2])
    UTP.Abs.LT exp1 exp2 -> prPrec i 5 (concatD [prt 0 exp1, doc (showString "<"), prt 0 exp2])
    UTP.Abs.LE exp1 exp2 -> prPrec i 5 (concatD [prt 0 exp1, doc (showString "<="), prt 0 exp2])
    UTP.Abs.GT exp1 exp2 -> prPrec i 5 (concatD [prt 0 exp1, doc (showString ">"), prt 0 exp2])
    UTP.Abs.GE exp1 exp2 -> prPrec i 5 (concatD [prt 0 exp1, doc (showString ">="), prt 0 exp2])
    UTP.Abs.PVar dynvar -> prPrec i 6 (concatD [prt 0 dynvar])
    UTP.Abs.PExpr exp -> prPrec i 6 (concatD [doc (showString "E"), prt 0 exp])
    UTP.Abs.PType type_ -> prPrec i 6 (concatD [doc (showString "T"), prt 0 type_])
    UTP.Abs.PredTX dynvar preds -> prPrec i 6 (concatD [prt 0 dynvar, doc (showString "(."), prt 0 preds, doc (showString ".)")])

instance Print [UTP.Abs.Pred] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print UTP.Abs.Exp where
  prt i = \case
    UTP.Abs.ECat exp1 exp2 -> prPrec i 0 (concatD [prt 1 exp1, doc (showString "++"), prt 0 exp2])
    UTP.Abs.ECons exp1 exp2 -> prPrec i 0 (concatD [prt 1 exp1, doc (showString ":"), prt 0 exp2])
    UTP.Abs.EAdd exp1 exp2 -> prPrec i 1 (concatD [prt 1 exp1, doc (showString "+"), prt 2 exp2])
    UTP.Abs.ESub exp1 exp2 -> prPrec i 1 (concatD [prt 1 exp1, doc (showString "-"), prt 2 exp2])
    UTP.Abs.EMul exp1 exp2 -> prPrec i 2 (concatD [prt 2 exp1, doc (showString "*"), prt 3 exp2])
    UTP.Abs.EDiv exp1 exp2 -> prPrec i 2 (concatD [prt 2 exp1, doc (showString "div"), prt 3 exp2])
    UTP.Abs.EMod exp1 exp2 -> prPrec i 2 (concatD [prt 2 exp1, doc (showString "mod"), prt 3 exp2])
    UTP.Abs.ENeg exp -> prPrec i 2 (concatD [doc (showString "neg"), prt 3 exp])
    UTP.Abs.EInt n -> prPrec i 3 (concatD [prt 0 n])
    UTP.Abs.EVar dynvar -> prPrec i 3 (concatD [prt 0 dynvar])
    UTP.Abs.EBool boolean -> prPrec i 3 (concatD [prt 0 boolean])
    UTP.Abs.ENil -> prPrec i 3 (concatD [doc (showString "nil")])
    UTP.Abs.ENmdTuple dynvar exps -> prPrec i 3 (concatD [prt 0 dynvar, doc (showString "("), prt 0 exps, doc (showString ")")])

instance Print [UTP.Abs.Exp] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print UTP.Abs.Type where
  prt i = \case
    UTP.Abs.TFun type_1 type_2 -> prPrec i 0 (concatD [prt 1 type_1, doc (showString "->"), prt 0 type_2])
    UTP.Abs.TRec dynvar types -> prPrec i 1 (concatD [prt 0 dynvar, doc (showString "(:"), prt 2 types, doc (showString ":)")])
    UTP.Abs.TProd dynvar types -> prPrec i 2 (concatD [prt 0 dynvar, prt 3 types])
    UTP.Abs.TArb -> prPrec i 3 (concatD [doc (showString "ttop")])
    UTP.Abs.TVar dynvar -> prPrec i 3 (concatD [prt 0 dynvar])
    UTP.Abs.TBot -> prPrec i 3 (concatD [doc (showString "tbot")])

instance Print [UTP.Abs.Type] where
  prt 3 [] = concatD []
  prt 3 (x:xs) = concatD [prt 3 x, prt 3 xs]
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 2 x]
  prt _ (x:xs) = concatD [prt 2 x, doc (showString "|"), prt 2 xs]
