-- File generated by the BNF Converter (bnfc 2.9.7).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -Wno-unused-matches #-}

module UTP.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified UTP.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transExp :: UTP.Abs.Exp -> Result
transExp x = case x of
  UTP.Abs.EAdd exp1 exp2 -> failure x
  UTP.Abs.ESub exp1 exp2 -> failure x
  UTP.Abs.EMul exp1 exp2 -> failure x
  UTP.Abs.EDiv exp1 exp2 -> failure x
  UTP.Abs.EInt integer -> failure x
