-- File generated by the BNF Converter (bnfc 2.9.7).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -Wno-unused-matches #-}

module UTP.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified UTP.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transBoolean :: UTP.Abs.Boolean -> Result
transBoolean x = case x of
  UTP.Abs.Boolean string -> failure x

transDynVar :: UTP.Abs.DynVar -> Result
transDynVar x = case x of
  UTP.Abs.DynVar string -> failure x

transPred :: UTP.Abs.Pred -> Result
transPred x = case x of
  UTP.Abs.PEqv pred1 pred2 -> failure x
  UTP.Abs.PImpl pred1 pred2 -> failure x
  UTP.Abs.POr pred1 pred2 -> failure x
  UTP.Abs.PAnd pred1 pred2 -> failure x
  UTP.Abs.PNot pred -> failure x
  UTP.Abs.EQ exp1 exp2 -> failure x
  UTP.Abs.NE exp1 exp2 -> failure x
  UTP.Abs.LT exp1 exp2 -> failure x
  UTP.Abs.LE exp1 exp2 -> failure x
  UTP.Abs.GT exp1 exp2 -> failure x
  UTP.Abs.GE exp1 exp2 -> failure x
  UTP.Abs.PVar dynvar -> failure x
  UTP.Abs.PExpr exp -> failure x
  UTP.Abs.PType type_ -> failure x
  UTP.Abs.PredTX dynvar preds -> failure x

transExp :: UTP.Abs.Exp -> Result
transExp x = case x of
  UTP.Abs.ECat exp1 exp2 -> failure x
  UTP.Abs.ECons exp1 exp2 -> failure x
  UTP.Abs.EAdd exp1 exp2 -> failure x
  UTP.Abs.ESub exp1 exp2 -> failure x
  UTP.Abs.EMul exp1 exp2 -> failure x
  UTP.Abs.EDiv exp1 exp2 -> failure x
  UTP.Abs.EMod exp1 exp2 -> failure x
  UTP.Abs.ENeg exp -> failure x
  UTP.Abs.EInt integer -> failure x
  UTP.Abs.EVar dynvar -> failure x
  UTP.Abs.EBool boolean -> failure x
  UTP.Abs.ENil -> failure x
  UTP.Abs.ENmdTuple dynvar exps -> failure x

transType :: UTP.Abs.Type -> Result
transType x = case x of
  UTP.Abs.TFun type_1 type_2 -> failure x
  UTP.Abs.TData dynvar types -> failure x
  UTP.Abs.TArb -> failure x
  UTP.Abs.TVar dynvar -> failure x
  UTP.Abs.TBot -> failure x
