-- File generated by the BNF Converter (bnfc 2.9.7).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -Wno-unused-matches #-}

module UTP.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified UTP.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transDynVar :: UTP.Abs.DynVar -> Result
transDynVar x = case x of
  UTP.Abs.DynVar string -> failure x

transTheory :: UTP.Abs.Theory -> Result
transTheory x = case x of
  UTP.Abs.Thry dynvar dynvars items -> failure x

transItem :: UTP.Abs.Item -> Result
transItem x = case x of
  UTP.Abs.DeclVar varclass dynvar varrole -> failure x
  UTP.Abs.DeclDLVar varclass dynvar dynvars -> failure x
  UTP.Abs.DeclASet varclass dynvar -> failure x
  UTP.Abs.Conj dynvar term -> failure x
  UTP.Abs.Law lawtype dynvar term -> failure x

transVarRole :: UTP.Abs.VarRole -> Result
transVarRole x = case x of
  UTP.Abs.VMR_KV sbbl type_ -> failure x

transVarClass :: UTP.Abs.VarClass -> Result
transVarClass x = case x of
  UTP.Abs.VarObs -> failure x
  UTP.Abs.VarExp -> failure x
  UTP.Abs.VarPred -> failure x

transSBBL :: UTP.Abs.SBBL -> Result
transSBBL x = case x of
  UTP.Abs.SBBL_NA -> failure x
  UTP.Abs.SBBL_SB -> failure x
  UTP.Abs.SBBL_NS -> failure x

transLawType :: UTP.Abs.LawType -> Result
transLawType x = case x of
  UTP.Abs.LAxiom -> failure x
  UTP.Abs.LProof -> failure x
  UTP.Abs.LAssume -> failure x

transTerm :: UTP.Abs.Term -> Result
transTerm x = case x of
  UTP.Abs.PEqv term1 term2 -> failure x
  UTP.Abs.PImpl term1 term2 -> failure x
  UTP.Abs.POr term1 term2 -> failure x
  UTP.Abs.PAnd term1 term2 -> failure x
  UTP.Abs.PNot term -> failure x
  UTP.Abs.EQ term1 term2 -> failure x
  UTP.Abs.NE term1 term2 -> failure x
  UTP.Abs.LT term1 term2 -> failure x
  UTP.Abs.LE term1 term2 -> failure x
  UTP.Abs.GT term1 term2 -> failure x
  UTP.Abs.GE term1 term2 -> failure x
  UTP.Abs.PTrue -> failure x
  UTP.Abs.PFalse -> failure x
  UTP.Abs.PVar dynvar -> failure x
  UTP.Abs.LCat term1 term2 -> failure x
  UTP.Abs.LCons term1 term2 -> failure x
  UTP.Abs.EAdd term1 term2 -> failure x
  UTP.Abs.ESub term1 term2 -> failure x
  UTP.Abs.EMul term1 term2 -> failure x
  UTP.Abs.EDiv term1 term2 -> failure x
  UTP.Abs.EMod term1 term2 -> failure x
  UTP.Abs.ENeg term -> failure x
  UTP.Abs.EInt integer -> failure x
  UTP.Abs.EVar dynvar -> failure x
  UTP.Abs.ETrue -> failure x
  UTP.Abs.EFalse -> failure x
  UTP.Abs.ENil -> failure x
  UTP.Abs.TCons dynvar terms -> failure x

transType :: UTP.Abs.Type -> Result
transType x = case x of
  UTP.Abs.TFun type_1 type_2 -> failure x
  UTP.Abs.TRec dynvar types -> failure x
  UTP.Abs.TProd dynvar types -> failure x
  UTP.Abs.TArb -> failure x
  UTP.Abs.TVar dynvar -> failure x
  UTP.Abs.TBot -> failure x
