-- File generated by the BNF Converter (bnfc 2.9.7).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -Wno-unused-matches #-}

module SkelUTP where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified AbsUTP

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transExp :: AbsUTP.Exp -> Result
transExp x = case x of
  AbsUTP.EAdd exp1 exp2 -> failure x
  AbsUTP.ESub exp1 exp2 -> failure x
  AbsUTP.EMul exp1 exp2 -> failure x
  AbsUTP.EDiv exp1 exp2 -> failure x
  AbsUTP.EInt integer -> failure x
